import type { Metadata } from 'next'
import LocalFont from 'next/font/local'
import './globals.css'
import Script from 'next/script'

import Header from '@/components/header'
import Footer from '@/components/footer'

const generalSans = LocalFont({
    variable: '--font-general-sans',
    src: [
        {
            path: '../public/fonts/GeneralSans-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../public/fonts/GeneralSans-Italic.woff2',
            weight: '400',
            style: 'italic',
        },
        {
            path: '../public/fonts/GeneralSans-Medium.woff2',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../public/fonts/GeneralSans-Semibold.woff2',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../public/fonts/GeneralSans-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],
})

export const metadata: Metadata = {
    title: 'GTMLab',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${generalSans.variable} antialiased`}>
                <Header />
                {children}
                <Footer />
                {/* HubSpot Tracking Code */}
                <Script
                    id="hs-script-loader"
                    src="//js-na2.hs-scripts.com/46392522.js"
                    strategy="afterInteractive"
                    async
                    defer
                />
            </body>
        </html>
    )
}
